# ARXOS extra Brave launch flags (debloat features without a managed-policy toggle).
--disable-brave-update
--no-pings
--disable-domain-reliability
--disable-background-networking
--force-dark-mode
# force dark on web content (pages), not just the UI chrome
--enable-features=WebContentsForceDark
--disable-features=BraveRewards,BraveWallet,BraveVPN,BraveAIChat
